ADMIN_EMAIL=${ADMIN_EMAIL:nexasphere@glbajajgroup.org}
ADMIN_PASSWORD=${ADMIN_PASSWORD:Admin@123}
CORS_ORIGIN=${CORS_ORIGIN:http://localhost:5173,https://nexasphere-glbajaj.vercel.app}
spring.datasource.url=${DB_URL:jdbc:h2:mem:nexaspheredb}
spring.datasource.driver-class-name=${DB_DRIVER:org.h2.Driver}
spring.datasource.username=${DB_USER:sa}
spring.datasource.password=${DB_PASS:}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
server.port=8080
